### ISSUE TITLE
Repeated sections that are slightly different--what am I doing wrong?

### ISSUE THREAD

**Issue by sgipianobuddha** [no-chris/chord-mark#635]
<img width="733" alt="From the ChordMark manual" src="https://github.com/no-chris/chord-mark/assets/148682967/ccd8c59b-fcbb-4a8b-9883-76ba3dddb8f3">
<img width="438" alt="My ChordMark code" src="https://github.com/no-chris/chord-mark/assets/148682967/ef980564-e1eb-4dea-bec0-d3d714e82902">
<img width="796" alt="This is what I get" src="https://github.com/no-chris/chord-mark/assets/148682967/358398e7-e026-4359-ac51-e5cd6721a580">

**Comment by no-chris** [comment]
Closing as this was discussed here https://github.com/no-chris/chord-chart-studio/issues/632
