### ISSUE TITLE
[Suggestion] chord-mark CLI

### ISSUE THREAD

**Issue by aztlan2k** [no-chris/chord-mark#661]
Hi @no-chris .  I came across your project recently and like what you've done.  I've always wondered why the dominant chord sheets format didn't have a better format that also represented the rhythm for a song.  Something that was more like the old style jazz chord sheets from Jazz Fake Books.  

For example...

![image](https://github.com/user-attachments/assets/9bb51cc4-4656-4656-8618-eabac9e92421)

So, I was happy to find your project.  Thanks for working on it and the associated Chord Chart Studio.

I was wondering if you might consider creating a command line (CLI) version based on your `chord-mark` library?  Something that can be used in a terminal to process files in a terminal and generate the more correct text rendering... and maybe the PDF version as well.

```sh
$ chord-mark song.txt
$ chord-mark --pdf song.txt
$ ls
song.cm   song.pdf  song.txt
```

I spent a few minutes trying to see if I could quickly load the `chord-mark` module to see if I could use it with Nodejs but unfortunately I was unable to get it to load properly.  Nodejs kept failing to load no matter what I tried.  Some sort of mixup between ES vs CommonJS module loading.

**Comment by no-chris** [comment]
That is interesting! can you explain a bit your use case for a CLI? I have to admit this was not on my radar yet

> I spent a few minutes trying to see if I could quickly load the chord-mark module to see if I could use it with Nodejs but unfortunately I was unable to get it to load properly. Nodejs kept failing to load no matter what I tried. Some sort of mixup between ES vs CommonJS module loading.

what is the exact issue? can you try pasting this code in a nodejs file? 
https://github.com/no-chris/chord-mark/tree/master/packages/chord-mark#usage

> I was wondering if you might consider creating a command line (CLI) version based on your chord-mark library? Something that can be used in a terminal to process files in a terminal and generate the more correct text rendering... and maybe the PDF version as well.

Currently the logic for text conversion is in Chord Chart Studio
https://github.com/no-chris/chord-chart-studio/blob/master/packages/chord-chart-studio/src/core/renderSong.js
Having the text output as a rendering option directly in chord-mark would make sense. Then exposing that through CLI would be trivial

The logic for formatting the layout for PDF conversion (there is no actual code for PDF conversion as this is done by the browser) is also in chord chart studio
https://github.com/no-chris/chord-chart-studio/blob/master/packages/chord-chart-studio/src/songRenderers/printPreview/helpers/mapLinesToColumns.js
PDF conversion directly in chord-mark would be trickier as it would require to actually generate the PDF with code.

**Comment by aztlan2k** [comment]
> can you explain a bit your use case for a CLI?

Oh, nothing to fancy. I just spend a lot of time in the terminal and can see myself essentially processing batches of chord-mark formated files -- which are easily created in a plain text editor, like vim -- to equivalent *.txt chord sheets, ready for printing.  

As for generating PDF's... if that's closely tied to the UI, well, without knowing too much of the code base at this point... maybe another node module can be used?  for example,

https://github.com/lorenzinigiovanni/simple-pdf-generator
https://github.com/foliojs/pdfkit

Here's the issue I see 

```sh
❯ pbpaste > index.js
❯ node --version
v22.5.1
❯ npm install --save chord-mark chord-mark-themes

added 5 packages in 2s
❯ node index.js
(node:84820) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/aztlan2k/Scratch/Nodejs/using-chord-mark/index.js:1
import { parseSong, renderSong } from 'chord-mark/lib/chord-mark.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1427:18)
    at Module._compile (node:internal/modules/cjs/loader:1449:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49

Node.js v22.5.1

```

if instead I use `index.mjs` or add `"type": "module"` to `package.json`, I get

```sh
❯ mv index.js index.mjs
❯ node index.mjs
file:///Users/aztlan2k/Scratch/Nodejs/using-chord-mark/index.mjs:1
import { parseSong, renderSong } from 'chord-mark/lib/chord-mark.js';
         ^^^^^^^^^
SyntaxError: Named export 'parseSong' not found. The requested module 'chord-mark/lib/chord-mark.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'chord-mark/lib/chord-mark.js';
const { parseSong, renderSong } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5)

Node.js v22.5.1
````

**Comment by aztlan2k** [comment]
@no-chris  As a test, do you think you can try creating a new, plain nodejs based project and install / import the `chord-mark` package?  Just to see if it works for you?

**Comment by no-chris** [comment]
Sorry for not replying sooner.
I cannot test it right now but can you try the commonJs syntax for importing the module?

```
const { parseSong, renderSong } = require('chord-mark/lib/chord-mark.js');
```

I guess the one in the sample will only work if you use a bundler

**Comment by aztlan2k** [comment]
Thanks @no-chris .    Here's what I get.

```sh
❯ cat index.js
// import { parseSong, renderSong } from './chord-mark/src/chordMark.js';
const { parseSong, renderSong } = require('chord-mark/lib/chord-mark.js');


const song = 'C.. G..\n' + 'When I _find myself in _times of trouble';

const parsed = parseSong(song);
const rendered = renderSong(parsed);%                                                                                                                                   
❯ yarn add chord-mark chord-mark-themes
yarn add v1.22.22
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
├─ chord-mark-themes@0.16.3
└─ chord-mark@0.16.3
info All dependencies
├─ chord-mark-themes@0.16.3
├─ chord-mark@0.16.3
├─ chord-symbol@4.0.0
└─ dompurify@3.1.6
✨  Done in 0.94s.
❯ node index.js
/Users/aztlan2k/Scratch/Nodejs/using-chord-mark/node_modules/chord-mark/lib/chord-mark.js:10
})(self, () => {
   ^

ReferenceError: self is not defined
    at Object.<anonymous> (/Users/aztlan2k/Scratch/Nodejs/using-chord-mark/node_modules/chord-mark/lib/chord-mark.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/aztlan2k/Scratch/Nodejs/using-chord-mark/index.js:2:35)

Node.js v22.5.1
```

**Comment by no-chris** [comment]
Hello

Sorry for not getting back sooner
This is an issue with the bundling, I fixed it but then I get an issue with the lib that I use to sanitize the user input that apparently does not work with NodeJs ootb
https://github.com/cure53/DOMPurify/issues/526

One solution could be to use a wrapper, I need to test further if this is the correct approach https://github.com/kkomelin/isomorphic-dompurify

Sorry about the trouble, will try to make progress on this in the next days!

**Comment by no-chris** [comment]
fixed in https://github.com/no-chris/chord-mark/pull/665

**Comment by no-chris** [comment]
Please use `chord-mark-jsdom` package in latest release `v0.17.0`
https://github.com/no-chris/chord-mark/tree/master/packages/chord-mark-jsdom
